version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: api-test
      POSTGRES_USER: raihan
      POSTGRES_PASSWORD: raihan123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6000:5432"

  backend:
    build:
      context: ./todo-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: raihan
      DB_PASSWORD: raihan123
      DB_DATABASE: api-test
    depends_on:
      - db

  frontend:
    build:
      context: ./todo-frontend
    ports:
      - "3001:80"
    env_file:
      - ./todo-frontend/.env
    depends_on:
      - backend

volumes:
  postgres-data:
